// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI/migrasyon işlemleri (db push, migrate deploy, seed) PgBouncer'ı atlayıp
    // doğrudan bağlantı kullanmalı. DIRECT_URL yoksa (örn. yerel geliştirmede) DATABASE_URL'e düşer.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
